---
title: "Chronic heart failure negatively impact muscle mass and bone mineral density: a wasting issue beyond the current spotlight"
author: "Kadek Adit Wiryadana"
date: "`r Sys.time()`"
output: 
  bookdown::html_document2:
    number_sections: false
    code_folding: hide
bibliography: ref.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Abstract
*--- see [abstract](#abs) at the end of the document ---*

---

### Introduction

### Methods

#### Search strategy and study inclusion

#### Data extraction and synthesis

#### Data Analysis
```{r library, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(googlesheets4)
library(gtsummary)
library(meta)
library(metafor)
library(PRISMA2020)
library(DT)
library(robvis)
```

### Results

```{r}
data <- read_sheet("https://docs.google.com/spreadsheets/d/1bVR6JFDdwcGuJiUJCh8uBhkvIABtRFWS4KGM85_aHNg/edit#gid=1037489593", sheet = 2)
```

```{r fig.align='center', fig.width=12, fig.height=4}
hip <- metacont(
  n.e = data$total_HF,
  mean.e = data$mean_H_HF,
  sd.e = data$SD_H_HF,
  n.c = data$total_control,
  mean.c = data$mean_H_control,
  sd.c = data$SD_H_control,
  studlab = paste0(first_author, year_publication),
  data = data,
  sm= "MD",
  random = TRUE,
  label.e = "CHF",
  label.c = "Control"
)

f_hip <- forest(hip)
f_hip
```
```{r fig.align='center', fig.width=6, fig.height=4}
lumbar <- metacont(
  n.e = total_V_HF,
  mean.e = mean_V_HF,
  sd.e = SD_V_HF,
  n.c = total_V_control,
  mean.c = mean_V_control,
  sd.c = SD_V_HF,
  sudlab = paste0(first_author, year_publication),
  data = data,
  sm= "MD",
  random = TRUE,
  label.e = "CHF",
  label.c = "Control"
)

f_lumbar <- forest(lumbar)
```

```{r}
hip <- metacont(
  n.e = ,
  mean.e = ,
  sd.e = ,
  n.c = ,
  mean.c = ,
  sd.c = ,
  studlab = ,
  data = ,
  sm= "MD",
  random = TRUE,
  label.e = ,
  label.c = 
  
)
```


### Discussion
*--- on construction ---*

### Disclosure
*--- on construction ---*

### References
<div id="refs"></div>

---

#### Abstract {#abs}

---

#### Software (session info)
```{r}
print("Analysis run by: Kadek Adit Wiryadana (wiryadana@wiryadana.org)")
sessionInfo()
```

```{bash}
cp chf_wasting.html index.html
```

